superglue/.babelrc.js, superglue/lib/components/RailsTag.js, superglue/package.json
Remove proptypes from the build, this was causing issues when importing the package.
Additionally, we import `attributesToProps` from html-react-parser instead of the package file, this was causing issues in esbuild.
=> Fix build and fix imports

superglue/lib/action_creators/requests.js, superglue/spec/lib/action_creators.spec.js
This adds a warning to remote when it tries to replace a page that has a different componentIdentifier that a received page. This can happen when you redirect to a completely new page using the current page's url via a form submit. And since remote doesn't navigate away from the current page, the current page component may receive props that are shaped differently.
=> Add warning for remote reqs

docs/page-response.md, superglue/lib/components/Nav.js, superglue_rails/lib/generators/rails/templates/edit.json.props, superglue_rails/lib/generators/rails/templates/index.json.props, superglue_rails/lib/generators/rails/templates/new.json.props, superglue_rails/lib/generators/rails/templates/show.json.props, superglue_rails/lib/install/templates/web/application.json.props, superglue_rails/superglue.gemspec
PropsTemplate will no longer camelize(:lower). Instead we must explicitly case our keys. This commit updates the generated layout to reflect that.
=> Update generated layout to use explicit cased keys

superglue/lib/utils/immutability.js, superglue/spec/lib/utils/immutability.spec.js
Previously superglue required that the page be shaped the exact same way in order to use `setIn`. That proved a bit too strict and cumbersome in situations where we want shape to be 1% different. For example, modals.
This removes that restriction
=> Relax setIn requirements

superglue_rails/lib/generators/rails/templates/edit.json.props, superglue_rails/lib/generators/rails/templates/new.json.props, superglue_rails/lib/generators/rails/templates/web/edit.js, superglue_rails/lib/generators/rails/templates/web/new.js
The react components generated by the scaffold generator use the `error` prop, but the the props_template loads this as `errors`
- also fixes hard-coded `post` in these forms
=> Fixes errors prop in scaffold form generator components

docs/README.md
We used to use CircleCI for build status badges. We have since moved to using GitHub Actions.
This commit updates the build status badge to use GitHub Actions.
Resolves #50
Ref:
- https://github.com/thoughtbot/superglue/issues/50
=> Use GitHub badge in the README

.github/workflows/schedule_rails_main.yml
We want to be prepared for possible breaking changes when Superglue uses the next version of rails.
Instead of running this as part of our CI on every contribution, we can run Superglue against Rails main on a schedule.
The job is scheduled to run on every Thursday.
=> Schedule superglue on Rails main

docs/tutorial.md, superglue_rails/lib/generators/rails/templates/web/edit.html.erb, superglue_rails/lib/generators/rails/templates/web/index.html.erb, superglue_rails/lib/generators/rails/templates/web/new.html.erb, superglue_rails/lib/generators/rails/templates/web/show.html.erb
Solves #52.
I tested this locally by installing my branch of superglue on a new Rails app. I then used a scaffold to generate files and ensured that the `erb` files showed the new `erblint:disable ErbSafety` comment.
=> Add erb-lint exception for ERB templates

superglue/.eslintrc.json, superglue/package.json
(https://github.com/thoughtbot/superglue/issues/66)
- Updated `.eslintrc.json` to use `@typescript-eslint/parser` and `@typescript-eslint/eslint-plugin`.
- Added TypeScript specific rules in the `overrides` section.
- Updated `package.json` to include a lint script that checks both JavaScript and TypeScript files in the `lib` folder.
=> Update ESLint config to support TypeScript

superglue/lib/utils/request.ts, superglue/spec/lib/utils/request.spec.js
https://github.com/thoughtbot/superglue/issues/63
This PR adds a warning message when a 406 response code is received. The warning message suggests the developer to add `format.json` to their `respond_to` block to handle remote calls properly.
Changes Made:
- Updated `handleServerErrors` function to log a warning message for 406 response codes.
- Added test cases to ensure the new functionality works as expected.
=> Add warning for 406 response code and test cases

docs/rails.md, superglue/lib/action_creators/requests.ts, superglue_rails/lib/generators/rails/templates/controller.rb.tt
This commit makes Superglue a bit smarter. Previously, content-location was used to specify the pageKey for 200s from non-get requests, but this was too cumbersome as the most common use case was setting the URL to be the referrer of the non-get request upon 200.
This uses that as the default logic but still accepts content-location if we want to explicitly override from the server, which is unlikely. Additionally I simplified the logic. We always want to use the response's URL unless in the case mentioned above. Existing tests pass.
=> Simplify the setting of pageKey

superglue/lib/action_creators/index.ts, superglue/lib/action_creators/requests.ts, superglue/lib/reducers/index.ts, superglue/lib/types/index.ts, superglue/spec/lib/reducers.spec.js
Incremental typing. I'm sure not everything is correct, but it'll improve as we type other parts of superglue. For now, i'm keeping close parity with what outputted to /dist, which is why you continue to see defaults on reducers.
=> Add type annotations for the reducers and state

superglue/lib/utils/url.ts
Add type annotations to utils/url
Resolves #75
=> Add type annotations to lib utils url

superglue/lib/action_creators/index.ts, superglue/lib/action_creators/requests.ts, superglue/lib/types/index.ts, superglue/lib/utils/react.ts, superglue/lib/utils/ujs.ts
This adds remote and visit type annotations. `npm run type-check` doesn't pass yet, but the output to dist is still acceptable. Its a step in the right direction.
=> Add remote and visit type annotations

superglue/lib/action_creators/requests.ts, superglue/lib/components/Nav.tsx, superglue/lib/index.tsx, superglue/lib/middleware.ts, superglue/lib/types/actions.ts, superglue/lib/types/index.ts, superglue/lib/types/requests.ts, superglue/lib/utils/immutability.ts, superglue/lib/utils/react.ts, superglue/lib/utils/url.ts, superglue/package.json, superglue/typedoc.json
This adds API documentation to most of the important methods exposed publically to a superglue dev. Its meant to be paired with a larger documentation website that is a wip.
=> Add typedoc

docs/recipes/modals.md
The file extension for the page to page file was .rb but should have been .js. This corrects it.
=> Correct page to page filename in modals.md

superglue/lib/action_creators/index.ts, superglue/lib/action_creators/requests.ts, superglue/lib/actions.ts, superglue/lib/components/Nav.tsx, superglue/lib/index.tsx, superglue/lib/middleware.ts, superglue/lib/reducers/index.ts, superglue/lib/types/actions.ts, superglue/lib/types/index.ts, superglue/lib/utils/react.ts, superglue/package.json, superglue/spec/lib/action_creators.spec.js, superglue/spec/lib/middleware.spec.js, superglue_rails/lib/install/templates/web/actions.js, superglue_rails/lib/install/templates/web/flash.js, superglue_rails/lib/install/templates/web/pages.js, superglue_rails/lib/install/templates/web/store.js, superglue_rails/lib/install/web.rb
This PR migrates most actions over to `createAction`. The goal of this is
1. Better typescript support using `.match` which allows us to use a [typescript guard](https://redux-toolkit.js.org/api/createAction#as-a-typescript-type-guard)
2. Easier for users. We previously exposed the const to the user so that they can createAction themselves before using it in a slice. Now they can just import it. For example:
```js
import { createSlice } from '@reduxjs/toolkit'
import { saveResponse, beforeVisit } from '@thoughtbot/superglue'
export const flashSlice = createSlice({
name: 'flash',
initialState: {},
extraReducers: (builder) => {
builder.addCase(beforeVisit, (state, action) => {
return {}
})
builder.addCase(saveResponse, (state, action) => {
const { page } = action.payload;
return {
...state, …
```
=> Migrate to `createAction`

.github/workflows/publish_docs.yml
This is so we can work on 1.0 without affecting the existing docs.
=> Manually trigger doc publishing

mkdocs.yml, superglue/lib/hooks/index.ts, superglue/lib/index.tsx, superglue/spec/lib/hooks.spec.jsx, superglue/typedoc.json
These are lightweight wrappers around Redux's `useSelector` and a nice, but must have convenience as we move away from `mapStateToProps`. This resolves #105
=> Introduce `usePage` and `useSuperglue` hooks.

superglue/lib/action_creators/requests.ts, superglue/lib/types/index.ts, superglue/spec/lib/action_creators.spec.js
This adjusts the suggestedAction logic to set to `none` if we click on a link that leads to the same page that you are currently on.
=> Remove navigation on same page

superglue/spec/features/navigation.spec.jsx, superglue/spec/lib/NavComponent.spec.jsx
This commit improves the variable names in the navigation tests to make them more descriptive.
=> Improve variable names in navigation tests

docs/requests.md, docs/ujs.md, superglue/lib/action_creators/requests.ts, superglue/lib/index.tsx, superglue/lib/types/index.ts, superglue/lib/types/requests.ts, superglue/lib/utils/request.ts, superglue/lib/utils/ujs.ts, superglue/spec/lib/action_creators.spec.js, superglue/spec/lib/utils/ujs.spec.js
This makes remote derive the target page key just like visit instead of
defaulting to the current key. It enables a far nicer dev ex when using
remote outside of ujs.
However when using data-sg-remote, we default to the current pagekey just
like before. Its better dev ex when using remote in UJS.
=> Default remote to a calculated key

docs/tutorial.md
There's an example using the old `props`. This PR aims to fix that using the `useContent` approach instead.
=> Updates tutorial documentation

docs/tutorial.md
In my React env, it's not possible to return multiple elements without a wrapping element or fragment, so the example code was not compiling.
=> In tutorial, add fragments around multiple elements

docs/tutorial.md
I'm very new to superglue, so I could very well be doing something silly, but the tutorial code wasn't working for me as written. I was getting an error:
> Uncaught TypeError: Cannot destructure property 'greet' of 'body' as it is undefined. at GreetShow (show.js:36:10)
Adding the useContent() make things work as expected.
=> In tutorial, add missing useContent() to show.js

docs/tutorial.md
The link was broken. It was pointing to
https://thoughtbot.github.io/superglue/tutorial/recipe/vite.md but should point to
https://thoughtbot.github.io/superglue/recipes/vite/
=> Fix link to Vite recipe in tutorial

superglue/lib/components/Navigation.tsx, superglue/spec/lib/NavComponent.spec.jsx
This fixes a issue where scroll restoration was not working as it was called before react renders the restored page. In this change we move the restoration to `useLayoutEffect`.
In reviewing the fix, we noticed that `setActivePage` was not being dispatched in `navigateTo`, and relied on `onHistoryChange` to make the correct changes. We refactor to move the explicit nav logic from `onHistoryChange` and back to `navigateTo`.
=> Use react lifecycle to manage scroll

superglue/lib/action_creators/index.ts, superglue/lib/action_creators/requests.ts, superglue/lib/components/Navigation.tsx, superglue/lib/index.tsx, superglue/lib/utils/request.ts, superglue/lib/utils/ujs.ts, superglue/lib/utils/url.ts, superglue/package.json, superglue/spec/helpers/polyfill.js, superglue/spec/helpers/setup.js, superglue/spec/lib/action_creators.spec.js, superglue/spec/lib/utils/request.spec.js, superglue/spec/lib/utils/url.spec.js
Fix dedup URL params
The depedency, url-parse, will dedup repeated url params. For example
`?fop=1&foo2` and will keep the first one. This doesn't play nicely with rails
Rack params as dups may indicate a structural array. This change migrates
`url-parse` to the browser's own 'URLSearchParams' and `URL`.
With the change, we had to:
1. Make minimal changes to `url.ts` helpers. You'll notice that we have a FAKE_ORIGIN as a fallback for the
`URL` usage, but in every instances, we have no 't need the origin at all. Either we replace the origin with a blank
or we only a part of the url like pathname.
2. baseUrl is required, but existing testing in isolation has it as optional. The update to the tests now reflect
that requirement
=> Fix dedup URL params

superglue/lib/utils/request.ts, superglue/spec/lib/utils/request.spec.js
Form data should override anything in the URL params First we delete every key. Then append the new keys accounting for duplicate keys that represent structural arrays.
=> Add coverage to form data serialization

superglue/lib/action_creators/index.ts, superglue/lib/action_creators/requests.ts, superglue/lib/action_creators/stream.ts, superglue/lib/actions.ts, superglue/lib/hooks/index.ts, superglue/lib/hooks/useFragment.tsx, superglue/lib/hooks/useStreamSource.tsx, superglue/lib/index.tsx, superglue/lib/reducers/index.ts, superglue/lib/types/index.ts, superglue/lib/types/requests.ts, superglue/lib/utils/helpers.ts, superglue/lib/utils/limited_set.ts, superglue/lib/utils/request.ts, superglue/package.json, superglue/spec/features/navigation.spec.jsx, superglue/spec/helpers/polyfill.js, superglue/spec/lib/action_creators.spec.js, superglue/spec/lib/cable_hook.spec.jsx, superglue/spec/lib/fragment_hook.spec.jsx, superglue/spec/lib/fragment_reducer.spec.js, superglue/spec/lib/fragments.spec.jsx, superglue/spec/lib/reducers.spec.js, superglue/spec/lib/stream_actions.spec.js, superglue/spec/lib/utils/request.spec.js, superglue/spec/support/store.jsx
This allows for a rails controller action like `create` (those that mutate) to render a view with just the fragments needed to update the referring page. There's no special vnd content type. Its all json and a render away.
Usage:
```
def create
...
if @post.save
redirect_to :back
else
render :create
end
end
```
and in create.json.props
```
superglue.broadcast_save_to_props(@post)
```
Would update the fragment and leave the current page url untouched.
=> Add support for stream responses

README.md
There was a typo in the README to the SSR docs. This corrected it.
=> Correct link to SSR docs in README
